version: "3.8"

services:
  fetch-challenge:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fetch-challenge
    ports:
      - "3000:3000"
    volumes:
      - ./database.sqlite:/app/database.sqlite
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
    command: npm run dev
